name: mmkcat
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.9.23
  - conda-forge::pytorch=1.12.1
  - conda-forge::numpy=1.23.5
  - conda-forge::pytorch-lightning=1.5
  - conda-forge::biopython=1.79
  - conda-forge::dssp=3.1.4
  - conda-forge::pip
  - conda-forge::einops
  - conda-forge::fairscale
  - conda-forge::hydra-core
  - conda-forge::omegaconf
  - conda-forge::openmm
  - conda-forge::pandas
  - conda-forge::pdbfixer
  - conda-forge::pytest
  - conda-forge::deepspeed
  - conda-forge::dm-tree
  - conda-forge::ml-collections
  - conda-forge::pyyaml
  - conda-forge::requests
  - conda-forge::scipy
  - conda-forge::tqdm
  - conda-forge::typing-extensions
  - conda-forge::wandb
  - conda-forge::scikit-learn
  - conda-forge::rdkit
  - conda-forge::seaborn
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - pip:
    - torch-geometric
    - fair-esm[esmfold]
    - git+https://github.com/NVIDIA/dllogger.git
    - git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307